version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
    - db
    volumes:
    - ./web:/var/www/html
    networks:
    - default
    ports:
    - 8080:80
  db:
    image: mysql:8.0
    restart: always
    networks:
    - default
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mainDB
    volumes:
    - persistent:/var/lib/mysql
    ports:
    - "8306:3306"
  phpadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    - web
    networks:
    - default
    ports:
    - 8081:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: changeme
volumes:
  persistent:
